blueprints/frontend/__init__.py
from __future__ import with_statement
import os
from flask import Blueprint, render_template, flash, redirect, request,url_for
from flask.ext.login import login_user, logout_user, current_user, login_required
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, validators
import sys
from login_manager import lm
from models import db, Donor, Donation
import tempfile
from num2words import num2words
from xhtml2pdf import pisa
from werkzeug import secure_filename
from jinja2 import Template
import os
import hashlib
import datetime
import random
import StringIO
import xlrd

from contextlib import closing
from zipfile import ZipFile, ZIP_DEFLATED

from flask import Blueprint, render_template, session, request, make_response, send_file, abort,  current_app, redirect, url_for
from jinja2 import Template
from xhtml2pdf import pisa
from sqlalchemy.orm import sessionmaker
from models import db, Donor, Donation

from emailHelper import sendEmail

frontend = Blueprint('frontend', __name__,
        template_folder=os.path.join(os.path.dirname(os.path.abspath(__file__)), 'templates'))

@lm.user_loader
def load_user(userid):
  print 'Load user being done '
  donor = Donor.query.filter_by(email_address=userid).first()
  print donor
  return donor

@frontend.route('donate', methods=['GET'])
@login_required
def donation_form_page():
    if current_user.is_admin:
        return render_template('DonationForm.html', donors=Donor.query.all())
    else:
        return current_app.login_manager.unauthorized()

@frontend.route("login", methods=["GET", "POST"])
def login():
  form = request.form
  if request.method == 'POST':

    donor = Donor.query.filter_by(email_address = form['email']).first()
    if donor is None:
      return redirect(url_for('.login'))
    if not donor.password_sha256 == hashlib.sha256(form['password']).hexdigest():
      print donor.password_sha256
      print hashlib.sha256(form['password']).hexdigest()
      donor = None
    # login and validate the user...
    if donor is None:
      return redirect(url_for('.login'))
    login_user(donor)
    flash("Logged in successfully.")
    # print "hi"+type(url_for(".donor_form_page"))
    return redirect(request.args.get("next") or url_for("frontend.view_donations"))
  return render_template("Login.html")

@frontend.route('logout', methods=['GET'])
def logout():
    logout_user()
    return redirect('login')

@frontend.route('createDonor', methods=['GET'])
@login_required
def donor_creation_page():
    if current_user.is_admin:
        return render_template('DonorCreation.html')
    else:
        return current_app.login_manager.unauthorized()

def fun(s):
    try:
        if(s[-1]=='/'):
            return int(s[:-1])
        else:
            return int(s)
    except Exception:
        return None

@frontend.route('donations', methods=['GET','POST'])
@login_required
def view_donations():
    #email = 'arunpandianp@gmail.com'
    email = current_user.email_address
    if request.method == 'GET':
        donor = db.session.query(Donor).filter_by(email_address = email).first()
        if donor.is_admin:
            donations=Donation.query.all()
        else:
            donations = donor.donations
        return render_template('view_donations.htm', donations=donations)
    elif request.method == 'POST':
        isemail = False
        if request.args.get('email'):
            isemail = True
        donation_ids = map(lambda x : fun(x),request.form.keys())
        print donation_ids
        donor = db.session.query(Donor).filter_by(email_address = email).first()
        if donor.is_admin:
            donations=Donation.query.filter(Donation.id.in_(donation_ids)).all()
        else:
            donations = donor.donations.all()
            donor_donation_ids = set(map(lambda x: x.id, donations))
            donor_accessible_donation_ids = []
            for i in donation_ids:
                if(i in donor_donation_ids):
                    donor_accessible_donation_ids.append(i)
            donation_ids = donor_accessible_donation_ids
            donations=Donation.query.filter(Donation.id.in_(donation_ids)).all()
            print donations
        return generate_zipped_receipts(donor, donations,isemail)
donation_made_text = '''Dear Donor,

  Thank you for making a difference by donating for Team Everest.  Please find your E-receips tattached with this email for your donation.

  Keep making a difference.

  Thanks & Regards,
  Team Everest
  www.teameverestindia.org
'''


def generate_zipped_receipts(donor, donations,isemail):
    pdfFiles = []
    for donation in donations:
        data = {'Amount':donation.amount, 'ReceiptNo':donation.id, 'DonationDate': donation.date, 'OrgName': "Team Everest", 'OrgAddress': "chennai", 'DonationMode': donation.mode, 'DonorName':donor.name, 'DonorAddress' : donor.address, 'Certification_Number' : "213213dsfdaf3", "WordAmount":num2words(donation.amount) }
        pdf = makePdf(data)
        pdfFiles.append(pdf)
    s = zipFiles(pdfFiles)
    if(isemail):
        file = open(s)
        sendEmail(donor.email_address, donation_made_text, file)
        return redirect(request.referrer) 
    response_body = open(s).read()
    os.remove(s)
    headers = {"Content-Disposition": "attachment; filename=receipt.zip"}
    return make_response((response_body,'200', headers))


"""take a list of file names and return a fd for the zipped file"""
def zipFiles(files):
    s = str(random.randint(0,10000000))
    s = "archivename"+s+".zip"
    z = ZipFile(s, "w", ZIP_DEFLATED)
    for f in files:
        z.write(f, f.split('/')[-1])
    z.close()
    return s

"""
gets data to be populated and creates the pdf
"""
def makePdf(data):
    if not data:
        raise Exception("null data in makeHtml");
    templateString = open("receipt_template.html").read()
    template = Template(templateString)
    html = template.render(data)
    return convertHtmlToPdf(html)

def convertHtmlToPdf(sourceHtml):
    resultFile = tempfile.NamedTemporaryFile(prefix='receipt_', suffix='.pdf', dir='/tmp', delete=False)
    # convert HTML to PDF
    pisaStatus = pisa.CreatePDF(
            sourceHtml,                # the HTML to convert
            dest=resultFile)           # file handle to recieve result
    return resultFile.name

blueprints/frontend/templates/BulkUpload.html
 <!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style type="text/css">
      body{
        padding-top: 70px;
      }
    </style>
  </head>

  <body>
    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">E-receipt Tool</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="nav navbar-nav">
            <li><a href="{{url_for('frontend.view_donations')}}">View Donation</a></li>
            <li><a href="{{url_for('frontend.donation_form_page')}}">Submit Donation Form</a></li>
            <li><a href="{{url_for('frontend.donor_creation_page')}}">Donor Creation</a></li>
            <li class="active"><a href="{{url_for('frontend.donor_creation_page')}}">Bulk Upload</a></li>
            <li><a href="logout">Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>



    <div class="container">
    <div class="jumbotron">

              <div class="text-center">

  <div class="row-fluid">
  <h2 class="rw-sentence">
  BULK UPLOAD

  </h2>
</div>
</div>


    <style type="text/css">
p {
    padding: 25px 50px;
}
</style>
      <form class="form-horizontal" role="form" enctype="multipart/form-data" method="post">


      <div class="form-group">
    <label for="pwd" class="col-xs-5 control-label"><h4>View the Upload Template File:</h4></label>
    <a href="Template.xlsx" class="col-xs-1 control-label" target="_blank"><h4>Template.xlsx</h4></a >
      </div>

      <div class="form-group">

      <label for="upload" class="col-xs-5 control-label">File Upload:</label>

      <form method="post" class="col-xs-5 control-label" role="form" enctype="multipart/form-data">
          <input type="file" class="col-xs-5 control-label" name="file" id="txtFileUpload" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"/>
        </div>


   <br>

  <div class="form-group">
  <div class="col-sm-offset-4 col-sm-8">

    <div class="checkbox col-xs-5 control-label">
     <label><input type="checkbox" onclick="if(this.checked) {this.form.action='/backend/excel?check=1'} else {this.form.action='/backend/excel'}"> Download in .zip format? </label>
    </div>
  </div>
  </div>


   <div class="form-group">
     <div class="col-sm-offset-4 col-sm-8">
    <p>
      <button type="submit" class="btn btn-primary">Submit</button>
    </p>
   </div>
      </div>
      </form>
</form>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  </body>
</html>

blueprints/frontend/templates/BulkUploadSuccess.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style type="text/css">
	    body{
	    	padding-top: 70px;
	    }
    </style>
  </head>

  <body>
    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    	<!-- Brand and toggle get grouped for better mobile display -->
    	<div class="container">
    		<div class="navbar-header">
    			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
    				<span class="sr-only">Toggle navigation</span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    			</button>
    			<a class="navbar-brand">E-receipt Tool</a>
    		</div>
    		<!-- Collect the nav links, forms, and other content for toggling -->
    		<div class="collapse navbar-collapse" id="navbarCollapse">
    			<ul class="nav navbar-nav">
    				<li><a href="/donations">View Donation</a></li>
    				<li><a href="/donate">Submit Donation Form</a></li>
    				<li><a href="/createDonor">Donor Creation</a></li>
    				<li><a href="{{ url_for('backend.upload') }}">Bulk Upload</a></li>
    				<li><a href="/logout">Logout</a></li>
    			</ul>
    		</div>
    	</div>
    </nav>


    <div class="container">
    <div class="jumbotron">

              <div class="text-center">

	<div class="row-fluid">
	<h2 class="rw-sentence">
	File Upload Successful...

	</h2>
</div>
</div>


    <style type="text/css">
p {
    padding: 25px 50px;
}
</style>

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  </body>
</html>

blueprints/frontend/templates/DonationForm.html
<!DOCTYPE html>

<script type="text/javascript">
function dropdownChange(value){
  if (value == "cash")
  {
    document.getElementById("cheque").style.display = "none";
    document.getElementById("chequeDate").value = "";
    document.getElementById("chequeNumber").value = "";
    document.getElementById("internet").style.display = "none";
    document.getElementById("transactionId").value = "";
  }else if (value == "cheque") {
    document.getElementById("cheque").style.display = "block";
	document.getElementById("transactionId").value="";
    document.getElementById("internet").style.display = "none";
  }else if (value == "internet") {
    document.getElementById("internet").style.display = "block";
    document.getElementById("cheque").style.display = "none";
    document.getElementById("chequeDate").value = "";
    document.getElementById("chequeNumber").value = "";
  }
}


function onSave()
{
  document.form1.action = "backend/create_donor"
    // document.Form1.target = "_blank";    // Open in a new window
    document.form1.submit();             // Submit the page
  return true;
}

function reset()
{
  document.getElementById("inputName").value = "";
  document.getElementById("inputPhone").value = "";
  document.getElementById("inputEmail").value = "";
  document.getElementById("inputAddress").value = "";
  document.getElementById("inputTown").value = "";
  document.getElementById("inputCountry").value = "";
}

function onSubmitAndDownload()
{
  document.form1.action = "backend/create_donation_and_return_pdf/"
    // document.Form1.target = "_blank";    // Open in a new window
    document.form1.submit();             // Submit the page
  return true;
  }

function onSubmit()
{
  document.form1.action = "backend/create_donation/"
    // document.Form1.target = "_blank";    // Open in a new window
    document.form1.submit();             // Submit the page
  return true;
}

function onSubmitAndSend()
{
  document.form1.action = "backend/create_donation_and_email_pdf/"
    // document.Form1.target = "_blank";    // Open in a new window
    document.form1.submit();             // Submit the page
  return true;
}
</script>

<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<style type="text/css">
body{
  padding-top: 70px;
}
</style>
</head>


<body>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>

    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    	<!-- Brand and toggle get grouped for better mobile display -->
    	<div class="container">
    		<div class="navbar-header">
    			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
    				<span class="sr-only">Toggle navigation</span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    			</button>
    			<a class="navbar-brand">E-receipt Tool</a>
    		</div>
    		<!-- Collect the nav links, forms, and other content for toggling -->
    		<div class="collapse navbar-collapse" id="navbarCollapse">
    			<ul class="nav navbar-nav">
    				<li ><a href="donations">View Donation</a></li>
    				<li class="active"><a href="donate">Submit Donation Form</a></li>
    				<li><a href="createDonor">Donor Creation</a></li>
    				<li><a href="backend/excel">Bulk Upload</a></li>
    				<li><a href="logout">Logout</a></li>
    			</ul>
    		</div>
    	</div>
    </nav>



<div class="container">
  <div class="jumbotron">

    <div class="text-center">

      <div class="row-fluid">
        <h2 class="rw-sentence">
          DONATION FORM
        </h2> <br>
      </div>
    </div>


    <style type="text/css">
 {
  padding: 25px 50px;
}
    </style>

    <form class="form-horizontal" id="form1" name="form1" method="post" role="form">

	    <div class="form-group col-xs-offset-2">
			<label for="donor" class="control-label col-xs-5">Select Donor </label>
			<div class="col-md-2 dropdown">
				<select class="form-control col-md-4 " name="donor" onChange="dropdownChange(this.value)">
					{% for donor in donors %}
				<option value="{{ donor.email_address }}">{{ donor.email_address }}</option>
					{% endfor %}
				</select>
			</div>
			<a type="button" class="btn btn-success btn-s" href="createDonor"> Add </a>
		</div>

      <div class="form-group">
        <label for="donationDate" class="control-label col-xs-5">Donation Date </label>
        <div class="col-md-2">
          <input type="date" class="form-control" id="donationDate" name="donationDate">
        </div>
      </div>

      <div class="form-group">
        <label for="donationAmount" class="control-label col-xs-5">Donation Amount </label>
        <div class="col-md-2">
          <input type="number" class="form-control" id="donationAmount" name="donationAmount">
        </div>
      </div>

      <div class="form-group">
        <label for="donationMode" class="control-label col-xs-5">Donation Mode </label>
        <div class="col-md-2 dropdown">
          <select class="form-control col-md-2" name="donationMode" onChange="dropdownChange(this.value)">
            <option value=""></option>
            <option value="cash">Cash</option>
            <option value="cheque">Cheque</option>
            <option value="internet">Internet</option>
          </select>
        </div>
      </div>


      <div id="cheque" style="display:none">
        <div class="form-group">
          <label for="chequeDate" class="control-label col-xs-5">Cheque Date </label>
          <div class="col-md-2">
            <input type="date" class="form-control" id="chequeDate" name="chequeDate">
          </div>
        </div>

        <div class="form-group">
          <label for="chequeNumber" class="control-label col-xs-5">Cheque Number </label>
          <div class="col-md-2">
            <input type="number" class="form-control" id="chequeNumber" name="chequeNumber">
          </div>
        </div>
      </div>

      <div id="internet" style="display:none">
        <div class="form-group">
          <label for="transactionId" class="control-label col-xs-5">Transaction Id </label>
          <div class="col-md-2">
            <input type="number" class="form-control" id="transactionId" name="transactionId">
          </div>
        </div>
      </div>

	    <div class="form-group col-sm-offset-2">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label class="col-sm-offset-4 col-sm-14 ">
          <input type="checkbox" name="download_pdf" value="download_pdf">Download receipt<br>
		  <input type="checkbox" name="email_pdf" value="email_pdf">Send Email<br>

        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary col-sm-offset-4" onClick="onSubmit()">Submit</button>
    </div>
  </div>



      <!--  <div class="control-label col-xs-6 col-xs-offset-1">
		<p>
			<input type="checkbox" name="download_pdf" value="download_pdf">Download receipt<br>
			<input type="checkbox" name="email_pdf" value="email_pdf">Send Email<br>
		</p>
          <br><p>
          <button type="submit" class="btn btn-primary btn-s" name="formSubmit" onClick="onSubmit()">Submit</button>
          button type="submit" class="btn btn-primary btn-s" name="formSubmitAndDownload" onClick="onSubmitAndDownload()" >Submit and Download e-Receipt</button>
          <button type="submit" class="btn btn-primary btn-s" name="formSubmitAndSend" onClick="onSubmitAndSend()">Submit and Send e-Receipt</button
          </p>
        </div>
      -->

    </form>
  </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
  </html>

blueprints/frontend/templates/DonorCreation.html
<!DOCTYPE html>
<script type="text/javascript">

function onSave()
{
    document.form1.action = "backend/create_donor/"
    // document.Form1.target = "_blank";    // Open in a new window
    document.form1.submit();             // Submit the page
    return true;
}

function reset()
{
    document.getElementById("inputName").value = "";
    document.getElementById("inputPhone").value = "";
    document.getElementById("inputEmail").value = "";
    document.getElementById("inputAddress").value = "";
    document.getElementById("inputTown").value = "";
    document.getElementById("inputCountry").value = "";
}


</script>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style type="text/css">
	    body{
	    	padding-top: 70px;
	    }
    </style>
  </head>

<body>
    <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    	<!-- Brand and toggle get grouped for better mobile display -->
    	<div class="container">
    		<div class="navbar-header">
    			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
    				<span class="sr-only">Toggle navigation</span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    			</button>
    			<a class="navbar-brand">E-receipt Tool</a>
    		</div>
    		<!-- Collect the nav links, forms, and other content for toggling -->
    		<div class="collapse navbar-collapse" id="navbarCollapse">
    			<ul class="nav navbar-nav">
    				<li ><a href="donations">View Donation</a></li>
    				<li ><a href="donate">Submit Donation Form</a></li>
    				<li class="active"><a href="createDonor">Donor Creation</a></li>
    				<li ><a href="backend/excel">Bulk Upload</a></li>
    				<li><a href="logout">Logout</a></li>
    			</ul>
    		</div>
    	</div>
    </nav>

    <div class="container">
    <div class="jumbotron">

              <div class="text-center">

	<div class="row-fluid">
	<h2 class="rw-sentence">
	DONOR CREATION FORM

	</h2>
</div>
</div>


    <style type="text/css">
p {
    padding: 25px 50px;
}
</style>
      <form class="form-horizontal" method="post" id="form1" name="form1" role="form">
  <div class="form-group">
    <label for="inputNameLabel" class="control-label col-xs-5">Name</label>
    <div class="col-md-4">
      <input type="text" class="form-control" id="inputName" placeholder="Name" name="name">
    </div>
  </div>

<div class="form-group">
    <label for="inputPhoneLabel" class="control-label col-xs-5">Contact No:</label>
    <div class="col-md-4">
      <input type="tel" class="form-control" id="inputPhone" placeholder="Phone" name="contact_number">

    </div>
  </div>

<div class="form-group">
    <label for="inputEmailLabel" class="control-label col-xs-5">Email</label>
    <div class="col-md-4">
      <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email">
    </div>
  </div>

<div class="form-group">
    <label for="inputAddressLabel" class="control-label col-xs-5">Address</label>
    <div class="col-md-4">
      <textarea class="form-control" id="inputAddress" rows="4" placeholder="Address" name="address"></textarea>
   </div>
   </div>

  <div class="form-group">
    <div class="col-md-offset-4 col-md-10">
      <button type="submit" class="btn btn-primary btn-s" onClick="onSave()">Save</button>
      <button type="reset" class="btn btn-primary btn-s" onClick="resetButton()">Reset</button>
    </div>
  </div>
</form>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

blueprints/frontend/templates/Login.html
<!DOCTYPE html>

<html>

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<style type="text/css">
body{
background-color: #FFFDFF;


  padding-top: 180px;
}
</style>
</head>


  <body>
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>
    <div class="container col-md-4 col-md-offset-4">
  <div class="jumbotron">

    <div class="text-center">

      <div class="row-fluid">
        <h2 class="rw-sentence" style="
    text-shadow: 0px 0px 7px rgba(0, 0, 0, 0.75);
    color: #0080ff;
    font-size: 30px;
font-family:Georgia">
          Welcome to <br>E-Receipt and Donation Management Tool!
        </h2> <br>
      </div>
    </div>

   <form class="form-horizontal" role="form" action="{{ url_for('.login') }}" method="POST">
  <div class="form-group col-xs-offset-2" >
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter Password" name="password">
  </div>

  <div class="checkbox col-md-offset-4">
    <label>
      <input type="checkbox"> Remember Me
    </label>
  </div>
  <button type="submit" class="btn btn-primary col-md-offset-4">Submit</button>
</form>

  </div>
  </div>


     <!-- </br></br></br></br></br></br>
      <div class="col-md-4 col-md-offset-4 vert-offset-top-2">
      <h2>Login</h2>
      <form class="form-horizontal" role="form" method="post" action="{{ url_for('.login') }}">
        <div class="form-group">

          <label for="email">Email:</label>
          <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
        </div>

        <div class="form-group">
          <label for="password">Password:</label>
          <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="password">
        </div>
        <div class="checkbox">
          <label><input type="checkbox"> Remember me</label>
        </div>
        <button type="submit" class="btn btn-primary" onClick="submitForm()">Submit</button>
      </form>
    </body>-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  </body>
</html>

blueprints/frontend/templates/Templatecsv.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </head>

  <body>
    <div class="container">
      </br></br></br></br></br></br>
      <div class="col-md-offset-2 vert-offset-top-4">
      <h2>Example Template</h2>
      <form class="form-horizontal" role="form">
        <div class="form-group">

	<table class="table table-bordered">
	     <thead>
	     <tr>
			<th data-field="name">Donor Name</th>
			<th data-field="contact_number">Contact No.</th>
			<th data-field="email_address">Email</th>
			<th data-field="address">Address</th>
			<th data-field="date">Donation Date</th>
			<th data-field="amount">Donation Amount</th>
			<th data-field="mode">Mode of Payment</th>
			<th data-field="cheque_number">Cheque Number</th>
			<th data-field="cheque_date">Cheque Date</th>	
			<th data-field="transaction_id">Transaction Id</th>	
	       </tr>
    	       </thead>
{% for record in records %}
	     <tr>
			<th data-field="name">{{ record.DonorName }}</th>
			<th data-field="contact_number">{{ record.ContactNo }}</th>
			<th data-field="email_address">{{ record.Email }}</th>
			<th data-field="address">{{ record.Address }}</th>
			<th data-field="date">{{ record.DonationDate }}</th>
			<th data-field="amount">{{ record.DonationAmount }}</th>
			<th data-field="mode">{{ reocord.ModeofPayment }}</th>
			<th data-field="cheque_number">{{ record.ChequeNumber }}</th>
			<th data-field="cheque_date">{{ record.ChequeDate }}</th>	
			<th data-field="transaction_id">{{ record.TransactionId }}</th>	
	    </tr>
{% endfor %}

	</table>
	</div>
       </form>
   </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

blueprints/frontend/templates/test.html
<!DOCTYPE html>
<html lang="en">
  <head>
  </head>
  <body>
    <h1>Hello, world!</h1>
  </body>
</html>